export enum ProjectStatus {
  BASIC_STUDIES = 'BASIC_STUDIES',
  DESIGN_IN_PROCESS = 'DESIGN_IN_PROCESS',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CHANGE_REQUESTED = 'CHANGE_REQUESTED',
  CHANGE_PENDING = 'CHANGE_PENDING',
  APPROVED = 'APPROVED'
}
