export enum Specialty {
  ARCHITECTURE = 'ARCHITECTURE',
  STRUCTURES = 'STRUCTURES',
  HSA = 'HSA',
  TOPOGRAPHY = 'TOPOGRAPHY',
  SANITATION= 'SANITATION',
  ELECTRICITY = 'ELECTRICITY',
  COMMUNICATIONS = 'COMMUNICATIONS',
  NON_APPLICABLE = 'NON_APPLICABLE'
}
